### PR TITLE
Multiple model names in /hardware, fix architecture

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

`./run`

Check https://certification-ubuntu-com-canonical-web-and-design-pr-30.run.demo.haus/hardware/201806-26281 roughly matches https://certification.ubuntu.com/hardware/201806-26281/ (without the "Download" buttons):

- [ ] All model names in heading
- [ ] Mentions "s390x"

Maybe also try other pages on https://certification-ubuntu-com-canonical-web-and-design-pr-30.run.demo.haus/

### CODE REVIEW

**Comment by codersquid** [comment]
It looks good, though I've found another difference. The opening paragraph has "desktop" hardcoded. The certifiedmodels api has the value in "category". You're passing category on to the template with this change, so it would be very simple to use it there too.

**Review by codersquid — CHANGES_REQUESTED** [review]
There are a few places where "Desktop" or "desktop" is hardcoded in text and in urls. Use {{ category }} to drive that.

**Comment by codersquid** [comment]
I found a bug on our existing site where the hardware manufacturer url isn't displayed even though we have a template snippet for it. If you want to add a bit to your template to handle it, you can get the info from certifiedmodeldetails in hardware_website. But I won't block approval just due to that.

**Comment by codersquid** [comment]
I made a PR to add download links to your branch. https://github.com/nottrobin/certification.ubuntu.com/pull/1

**Comment by codersquid** [comment]
I'll be happy to +1 if the "desktop" text is taken care of. I will rebase my PR off of master once your PR lands.

**Comment by nottrobin** [comment]
Thanks for finding all those @codersquid. I've updated it to use the `category` variable.

But this will lead to the category sometimes saying "ubuntu core", which does match [some cases on the production site](https://certification.ubuntu.com/hardware/201808-26450/), but I noticed [some others on the live site](https://certification.ubuntu.com/hardware/201805-26256/) say e.g. "The Intel NUC7CJYH iot gateway", but the category [from the API](https://certification.canonical.com/api/v1/certifiedmodels/?format=json&canonical_id=201805-26256) is still "Ubuntu Core". How could I achieve the "iot gateway" wording? Does it matter?

I also noticed that we were always including "pre-installed" wording, even when the category was only "Certified" rather than "Enabled". I fixed that, but I want to check my interpretation here is correct:

- Am I right in thinking that every single model will always be either "Certified" or "Enabled"? Or are
there some models that aren't certified?
- Is "Enabled" effectively the superior one here? As in, is my logic correct that if any "releases" are "Enabled" then we can say "is certified pre-installed for Ubuntu", but if not then we have to just say "certified for Ubuntu"?

**Comment by nottrobin** [comment]
@codersquid Oh another thing - I would have assumed that the "Available from ubuntu.com" wording only really makes sense if there's a download URL, so that should probably use the same logic about download URLs from your PR - is that right?

I added a comment on https://github.com/canonical-web-and-design/certification.ubuntu.com/pull/37#issuecomment-525188224 about that.

**Comment by codersquid** [comment]
> But this will lead to the category sometimes saying "ubuntu core", which does match some cases on the production site, but I noticed some others on the live site say e.g. "The Intel NUC7CJYH iot gateway", but the category from the API is still "Ubuntu Core". How could I achieve the "iot gateway" wording? Does it matter?

I've opened a bug for this on our side.

**Comment by codersquid** [comment]
> Am I right in thinking that every single model will always be either "Certified" or "Enabled"? Or are
> there some models that aren't certified?

You are. When the models aren't certified they aren't included in the response

> 
> Is "Enabled" effectively the superior one here? As in, is my logic correct that if any "releases" are "Enabled" then we can say "is certified pre-installed for Ubuntu", but if not then we have to just say "certified for Ubuntu"?

Your logic is correct. Deciding which is superior is philosophical.

**Comment by codersquid** [comment]
> Oh another thing - I would have assumed that the "Available from ubuntu.com" wording only really makes sense if there's a download URL, so that should probably use the same logic about download URLs from your PR - is that right?

I'll include that text in my PR or this will grow to a Frankenstein monster PR.

**Review by codersquid — APPROVED** [review]

**Review by pmahnke — APPROVED** [review]
looks good

**Pull request merged**
